### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'top' in shadow node of type: FastImageView

### ISSUE THREAD

**Issue by xxinjun** [DylanVann/react-native-fast-image#270]
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'top' in shadow node of type: FastImageView
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(Unknown Source:121)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(Unknown Source:10)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(Unknown Source:24)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(Unknown Source:0)
	at com.facebook.react.uimanager.UIImplementation.createView(Unknown Source:39)
	at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:59)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:278)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:23)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:166)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source:16)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPositionValues argument 1 has type int, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(Unknown Source:47)
	... 15 more
java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPositionValues argument 1 has type int, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(Unknown Source:47)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(Unknown Source:10)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(Unknown Source:24)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(Unknown Source:0)
	at com.facebook.react.uimanager.UIImplementation.createView(Unknown Source:39)
	at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:59)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:278)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:23)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:166)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source:16)
	at java.lang.Thread.run(Thread.java:784)

**Comment by Sangrene** [comment]
Any news on this ?
