### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by lightninglu10** [DylanVann/react-native-fast-image#349]
When running `react-native link react-native-fast-image`, I get the error 

Cannot read property 'match' of undefined

Stack trace is below:

```
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (....react-native/local-cli/link/pods/findLineToAddPod.js:22:13)
    at getLinesToAddEntry (....node_modules/react-native/local-cli/link/pods/registerNativeModule.js:36:8)
    at registerNativeModulePods (....node_modules/react-native/local-cli/link/pods/registerNativeModule.js:25:21)
    at Object.registerNativeModule [as register] (....node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:13:1)
    at ....node_modules/react-native/local-cli/link/link.js:74:12
    at Array.forEach (<anonymous>)
    at linkDependency$ (....node_modules/react-native/local-cli/link/link.js:44:28)
    at tryCatch (....node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] ....node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (....node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
```

**Comment by huxiaonb** [comment]
same err

**Comment by huxiaonb** [comment]
add the following line in your Podfile after existing pod '[...] lines:
**# Add new pods below this line**
[https://github.com/facebook/react-native/issues/16774#issuecomment-350999013](url)
[https://medium.com/@sroze/react-native-cannot-read-property-match-of-undefined-997091a019ea](url)

**Comment by lightninglu10** [comment]
Closing as not planned: filed years ago, a workaround was shared in the thread, and the repo has been inactive for a long time. Happy to re-open with fresh details if this still bites on current versions.
