### ISSUE TITLE
Android "Unable to find GlideModule implementation" in release mode

### ISSUE THREAD

**Issue by Andarius** [DylanVann/react-native-fast-image#356]
When running the app on Android on release mode, it crashes as soon as it tries to render a FastImage component.  

```
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-fast-image": "^5.1.1"
```

I added in `/android/app/proguard-rules.pro` (as mentioned [#180](https://github.com/DylanVann/react-native-fast-image/issues/180) )
```
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
```

Full Stacktrace:
```
-27 01:28:26.816  4680  4680 E AndroidRuntime: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.f.e.a(Unknown Source:59)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.f.e.a(Unknown Source:128)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.b(Unknown Source:25)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.e(Unknown Source:5)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.d(Unknown Source:15)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.b(Unknown Source:11)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.f(Unknown Source:5)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.e.c(Unknown Source:0)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(Unknown Source:6)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(Unknown Source:0)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.ViewManager.createView(Unknown Source:0)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.k.a(Unknown Source:35)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.ao$e.a(Unknown Source:23)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.ao$h.c(Unknown Source:60)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.ao$h.a(Unknown Source:23)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.uimanager.e.b(Unknown Source:0)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.modules.core.e$b.b(Unknown Source:48)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.facebook.react.modules.core.a$a$1.doFrame(Unknown Source:2)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:851)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:739)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6753)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-27 01:28:26.816  4680  4680 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.Class.forName(Class.java:453)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.Class.forName(Class.java:378)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at com.c.a.f.e.a(Unknown Source:0)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        ... 28 more
11-27 01:28:26.816  4680  4680 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp3.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/com.myapp.recognition-sdtQL5m14cinXaOavIMdAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.recognition-sdtQL5m14cinXaOavIMdAQ==/lib/arm, /data/app/com.myapp.recognition-sdtQL5m14cinXaOavIMdAQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-27 01:28:26.816  4680  4680 E AndroidRuntime:        ... 32 more
```

**Comment by oneroman** [comment]
it seems used to work fine in v4; but in v5 something is broken

**Comment by Andarius** [comment]
@oneroman solution posted here [#180](https://github.com/DylanVann/react-native-fast-image/issues/180) works for me

```
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```
