### ISSUE TITLE
 java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap

### ISSUE THREAD

**Issue by prateekchachra** [DylanVann/react-native-fast-image#592]
I'm getting this bug on running FastImage on react-native version 0.60.2 and this error iis a blocker that I cant figure out. any help?

**Comment by mohity777** [comment]
is there any solution?? i am facing this issue too

**Comment by shay-te** [comment]
also here same issue
happens when changing state 

```
FATAL EXCEPTION: main
Process: com.objectivelove, PID: 11268
java.lang.ClassCastException: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap
	at com.facebook.react.bridge.ReadableNativeArray.getMap(ReadableNativeArray.java:112)
	at com.facebook.react.bridge.ReadableNativeArray.getMap(ReadableNativeArray.java:22)
	at com.dylanvann.fastimage.FastImageViewModule$1.run(FastImageViewModule.java:36)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
