### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError android.app.Activity.isDestroyed

### ISSUE THREAD

**Issue by fonov** [DylanVann/react-native-fast-image#595]
**Describe the bug**
crash app from crashlytics

```
Fatal Exception: java.lang.NoSuchMethodError: android.app.Activity.isDestroyed
       at com.dylanvann.fastimage.FastImageViewManager.isActivityDestroyed(FastImageViewManager.java)
       at com.dylanvann.fastimage.FastImageViewManager.isValidContextForGlide(FastImageViewManager.java)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.addRootView(NativeViewHierarchyManager.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:524)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
device info

```
Brand: samsung
Model: Galaxy S3 Mini
Orientation: Portrait
RAM free: 149.41 MB
Disk free: 3.18 GB
Version: 4.1.2
Orientation: Portrait
Rooted: No
```
**Screenshots**

**Dependency versions**

```
"react": "16.9.0",
"react-native-fast-image": "^7.0.2",
"react-native": "0.61.4",
```

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by michiel1995** [comment]
Came across the same error. Has to do something with https://stackoverflow.com/questions/34508345/java-lang-nosuchmethoderror-activity-isdestroyed-below-api-17-handle/43545476

It can be fixed in the FastImageViewManager by adding a try catch block at `isActivityDestroyed` 
``
 try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                return activity.isDestroyed() || activity.isFinishing();
            } else {
                return activity.isDestroyed() || activity.isFinishing() || activity.isChangingConfigurations();
            }
        } catch(NoSuchMethodError error){

            return activity.isFinishing() || activity.isChangingConfigurations();
        }
``

**Comment by HessiPard** [comment]
Same Issue here

**Comment by kirillpisarev** [comment]
Also noticed the same "fatal" errors in my Sentry report. 
89% android 4.1.2, rest is android 4.1.1

**Comment by appli-intramuros** [comment]
Same issue here for android 4.1.2 ... any updates ?

**Comment by devagul93** [comment]
Getting the same error in crashlytics.... any updates ?

**Comment by sanjaypojo** [comment]
Experiencing production crashes due to this exact issue, has anyone had any luck with this?

**Comment by maleking** [comment]
For now you can set fallback props true until this crash fix by someone

**Comment by DylanVann** [comment]
Fixed in 8.6.0 (#921): below Android 4.2 (API 17), the destroyed-activity check no longer calls `Activity.isDestroyed()`. Please open a new issue if you still see this on the latest version.
