### ISSUE TITLE
Android error FastImageOkHttpProgressGlideModule.java

### ISSUE THREAD

**Issue by mezalejandro** [DylanVann/react-native-fast-image#670]
**Describe the bug**
On Crashlytics of firebase I have the error:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.Registry com.bumptech.glide.Registry.replace(java.lang.Class, java.lang.Class, com.bumptech.glide.load.model.ModelLoaderFactory)' on a null object reference

**Dependency versions**

- React Native version: 0.61.5
- React version: 16.9.0
- React Native Fast Image version: 7.0.2

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by nochkin** [comment]
Just to add, I also have the same exact issue using the latest versions:
React Native 0.62.2
React Native Fast Image 8.1.5

**Comment by felipeaugusto1** [comment]
I'm also facing this same issue

**Comment by danigm87** [comment]
Probably the same issue:
https://github.com/DylanVann/react-native-fast-image/issues/536

It seems to be a problem when running the application in the Nexus 5x emulator while google bots run the application to do some tests.

**Comment by volpejoaquin** [comment]
Any update ?

**Comment by anandchakru** [comment]
Here is the stack tract in case if its of any help,

On, LGE Nexus 5X v6.0.1 Portrait

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.i com.bumptech.glide.i.r(java.lang.Class, java.lang.Class, com.bumptech.glide.load.p.o)' on a null object reference
       at com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule.registerComponents(FastImageOkHttpProgressGlideModule.java)
       at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java)
       at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java)
       at com.bumptech.glide.Glide.get(Glide.java)
       at com.bumptech.glide.Glide.getRetriever(Glide.java)
       at com.bumptech.glide.Glide.with(Glide.java)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by akhan118** [comment]
Add this to  android/build.gradle

```
buildscript {
    ext {
        excludeAppGlideModule = true
    }
```

**Comment by anhkieet** [comment]
Same here! Do we have any updates on this issue?

**Comment by dhavalsulhuf** [comment]
getting issue same here. any solution for this issue?

![Screenshot 2023-04-27 at 11 11 44 AM](https://user-images.githubusercontent.com/109509977/234769587-1286ca02-7852-455b-87bf-c4824b3988dd.png)
