### ISSUE TITLE
Image not show on android, but still working on IOS

### ISSUE THREAD

**Issue by vinhtran6921** [DylanVann/react-native-fast-image#710]
**Describe the bug**
When I show image with url, android device not showing but still show on IOS
```
 <FastImage
                    source={{uri: 'https://via.placeholder.com/150/810b14'}
                    style={style}
                    resizeMode={resizeMode}
                    onLoadStart={this.onLoadStart}
                    onLoadEnd={this.onLoadEnd}
                />
```

**Dependency versions**

- React Native version: 0.62.2
- React Native Fast Image version: 8.3.0

**Comment by vinhtran6921** [comment]
Any helps?
I still stuck at this

**Comment by jordangrant** [comment]
@vinhtran6921 does a regular <Image> component show on Android?

**Comment by vinhtran6921** [comment]
Yes. <Image> will work but I want to use FastImage. How can I fix it?
Pls help

**Comment by jordangrant** [comment]
@vinhtran6921 does that url with http:// work? Do other urls work?

**Comment by tsdmrfth** [comment]
Same issue here. Images are not loaded. It works on iOS correctly. URL starts with https://

**Comment by vallvien** [comment]
Can this be a problem specifically related to images from `placeholder.com`? We are facing the same issue, this url `https://via.placeholder.com/300/09f/fff.png` works in the browser and on iOS but does not display the image on Android.
When `<FastImage />` is swapped with RN `<Image />` on Android, the same url works fine as well.

**Comment by mdoesburg** [comment]
Happens when upgrading package from 8.2.0 to 8.2.1+. Must be related to this [bug](https://github.com/DylanVann/react-native-fast-image/commit/ba0f238821ba23517b8e62e759f685b8cd67c0c6) fix.

**Comment by mdoesburg** [comment]
@milansusnjar Could you take a look at this, since the code linked to in my previous comment seems to be authored by you?

**Comment by bluenex** [comment]
I have just experienced this too. I have just upgraded to version `8.2.0`. There is no problem on iOS, only not show on Android. It also triggers `onError` but I haven't checked yet whether there is a message.

**Comment by milansusnjar** [comment]
@mdoesburg I tested it and it doesn't work with the image from your example but it works with another URL.
Doesn't work: `source={{uri: 'https://via.placeholder.com/150/810b14'}`
Works: `source={{uri: 'https://unsplash.it/400/400?image=1'}}`
The rest of the code is the same. I'm not sure how this could be connected with my PR.

**Comment by milansusnjar** [comment]
It doesn't work with v7.0.0 for me. 

Glide fails, here is the log from my phone:

```
2020-09-02 21:22:26.679 16922-16922/com.blogl10n W/Glide: Load failed for https://via.placeholder.com/150/810b14 with size [600x600]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    com.bumptech.glide.load.HttpException(Gone)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    com.bumptech.glide.load.HttpException(Gone)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.HttpException: Gone
2020-09-02 21:22:26.680 16922-16922/com.blogl10n I/Glide: Root cause (1 of 1)
    com.bumptech.glide.load.HttpException: Gone
        at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:73)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-09-02 21:22:26.693 16922-16922/com.blogl10n W/Glide: Load failed for https://via.placeholder.com/150/810b14 with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    com.bumptech.glide.load.HttpException(Gone)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    com.bumptech.glide.load.HttpException(Gone)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.HttpException: Gone
2020-09-02 21:22:26.695 16922-16922/com.blogl10n I/Glide: Root cause (1 of 1)
    com.bumptech.glide.load.HttpException: Gone
        at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:73)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

This is the code to reproduce
```
<FastImage
    style={{width: 200, height: 200}}
    source={{uri: 'https://via.placeholder.com/150/810b14'}}
    onError={(e) => { console.log('e', e); }}
    resizeMode={FastImage.resizeMode.contain}
/>
```

**Comment by TranDinhKhang** [comment]
I have this issue, too

**Comment by zabojad** [comment]
What I observe is that it seems to happen on Android versions < 9 only. Do you all confirm?

**Comment by byeokim** [comment]
I am having this issue on Android 10, with RNFI version of 8.3.4.

**Comment by zabojad** [comment]
OK, in my case, it was a SSL issue happening only on Android < 9 because the certificate did not support TLS V1.2

We are having different issues here. Would be useful if you guys could inspect and post here your logcats logs related to this issue... In my case, again, it was SSL handshake failing...

**Comment by byeokim** [comment]
Thank you. I found cause of my issue. Fast Image couldn't get images from server because request had been sent without session cookie in request header. iOS build has no problem with getting images. So it seems that it's Glide that doesn't automatically attach session cookie to request header.

**Comment by dragonlong206** [comment]
I am facing the same issue. @byeokim How do you resolve it?

**Comment by byeokim** [comment]
@dragonlong206 I haven't resolved yet. I am currently using `fallback` prop as @mdoesburg suggests while digging into solution.

**Comment by dragonlong206** [comment]
In my case, the problem is SSL certificate of image's server. It's an incomplete chain certificate. I can see the error in logcat.

**Comment by pqminh** [comment]
+1

**Comment by suwu150** [comment]
I also encountered this problem. After repeated testing, I found that only super long graph can cause this problem. Is there any solution

**Comment by cheese-git** [comment]
In my case, this problem is caused by not sending cookies to the server. I'm using axios(which uses `XMLHttpRequest` internally) to request session, and I solved this problem by simply installing `rn-fetch-blob`, which includes polyfills of `XMLHttpRequest`.

Maybe we could add `rn-fetch-blob` as a dependency/peerDependency of this library.

**Comment by hansanwok** [comment]
This works for me, use fallback if fast image can not load image
`const getUriImage = (uri) => {
  return uri !== null &&
    uri !== undefined &&
    uri.includes('/') &&
    uri.includes('.')
    ? uri
    : '';
};

const ProgressiveImage = (props) => {
  const {source} = props;

  const [hasError, setHasError] = useState(false);

  return source?.uri ? (
    <FastImage
      {...props}
      fallback={hasError}
      onError={() => setHasError(true)}
      source={{
        uri: getUriImage(source?.uri),
        cache: FastImage.cacheControl.immutable,
      }}
    />
  ) : (
    <Image {...props} />
  );
};
`

**Comment by hansanwok** [comment]
`eqweq`

**Comment by AD1N1993** [comment]
I have this issue, too

**Comment by avinashsahoo** [comment]
Anyone got a solution to this?

**Comment by dio-ralali** [comment]
facing the same issue here. anyone got solution?

package.json : 

"react-native-fast-image": "8.1.5",
"react-native": "^0.64.2",

**Comment by SDE-Arvind** [comment]
facing same issue, please provide solution for this

**Comment by Shafran123** [comment]
Try Commenting cache if you are using this works for me!

`cache:FastImage.cacheControl.cacheOnly  `

**Comment by amerllica** [comment]
Hi dear @byeokim, what should I add to the header?

```xml
<FastImage
  source={{
    uri: 'https://picsum.photos/536/354',
    headers: {
      key: 'value', // <== what should I add here?
    },
  }}
/>
```

**Comment by byeokim** [comment]
> Hi dear @byeokim, what should I add to the header?
> 
> ```
> <FastImage
>   source={{
>     uri: 'https://picsum.photos/536/354',
>     headers: {
>       key: 'value', // <== what should I add here?
>     },
>   }}
> />
> ```

Regarding my comments above I meant
```jsx
<FastImage
  source={{
    uri: ...,
  }}
  fallback={Platform.OS === 'android'}
/>
```

**Comment by iamnsrajput** [comment]
> > Hi dear @byeokim, what should I add to the header?
> > ```
> > <FastImage
> >   source={{
> >     uri: 'https://picsum.photos/536/354',
> >     headers: {
> >       key: 'value', // <== what should I add here?
> >     },
> >   }}
> > />
> > ```
> 
> Regarding my comments above I meant
> 
> ```js
> <FastImage
>   source={{
>     uri: ...,
>   }}
>   fallback={Platform.OS === 'android'}
> />
> ```

this worked for me 👍

**Comment by JieMin27** [comment]
Facing the same issue, is there any solutions?

**Comment by PiotrSzczepanekUk** [comment]
I had the same issue and I used this solution 
`fallback={Platform.OS === 'android'}`

**Comment by eyale** [comment]
I've faced same issue on Android emulator.
What I've did to fix it

1. I've added priority like so `priority: FastImage.priority.high,`
2. restarted my Android emulator
3. in terminal I've runned `adb reverse tcp:8081 tcp:8081`

Those three steps that helped me.

**Comment by jlmonroy13** [comment]
`"react-native-fast-image": "^8.5.11"`

Make sure you don't have any condition to hide the `<FastImage />` component while is loading (`display: 'none'`), if you are doing that the image on Android emulator will never load, I did the following and it is working for me on iOS and Android

```
const ImageAsset = ({ uri, maxHeight }: props) => {
  const [imageHeight, setImageHeight] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const { width: screenWidth } = Dimensions.get('window');

  if (!uri) return null;

  return (
    <Flex
      alignItems="center"
      style={[Styles.imageContainer, isLoading && Styles.minHeight]}
      justifyContent="center"
    >
      {isLoading && <ActivityIndicator />}

      <FastImage
        style={{
          width: '100%',
          position: isLoading ? 'absolute' : 'relative',
          opacity: isLoading ? 0 : 1,
          height: imageHeight,
        }}
        source={{ uri, priority: FastImage.priority.high }}
        onLoad={({ nativeEvent: { width, height } }) => {
          const aspectRatio = width / height;
          const heightScaled = screenWidth / aspectRatio;
          const heightToUpdate =
            heightScaled > maxHeight || !heightScaled
              ? maxHeight
              : heightScaled;
          setImageHeight(heightToUpdate);
          setIsLoading(false);
        }}
      />
    </Flex>
  );
};
```

**Comment by LunatiqueCoder** [comment]
in my case, I was trying to fetch from `localhost`. Replacing `localhost` with my IP worked! Hope this helps somebody.

**Comment by owjsub** [comment]
In my case, if the FastImage view is being resized while an image is loading, then it will cause the image to fail to load without triggering any callbacks, including any other FastImage views on the same screen. Can workaround these cases by enabling `fallback` which will use react-native `Image` instead.

```
Environment:
react-native-fast-image: 8.6.3
Nexus 7 and Nexus 10 API 29 Emulator
```

**Comment by T-Damer** [comment]
If I should use the fallback, why do I need the fast-image? Seems like we need another solution

**Comment by Norcy** [comment]
Still exist in FastImage but not in Image : https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2554028430.jpg

Only in Android.

In my case, I use this sample code to avoid blank image

```js
const [fallback, setFallback] = React.useState(false);
<FastImage
  onError={() => {
    if (Platform.OS === 'android') {
      setFallback(true);
    }
  }}
  fallback={fallback}
/>
```

**Comment by devsphere-apps** [comment]
This is work for me as well

` fallback={Platform.OS === 'android'}`
