### ISSUE TITLE
Cannot run RNFI on device with error java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by dashracer** [DylanVann/react-native-fast-image#72]
Hi @DylanVann ,

I'm trying to ru my app on android device but get this error.

```
Caused by: java.lang.InstantiationException: class com.dylanvann.fastimage.OkHttpProgressGlideModule has no zero argument constructor
                                                       at java.lang.Class.newInstance(Class.java:1563)
                                                       at com.bumptech.glide.module.ManifestParser.parseModule(ManifestParser.java:51)
                                                       at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:30) 
                                                       at com.bumptech.glide.Glide.parseGlideModules(Glide.java:187) 
                                                       at com.bumptech.glide.Glide.get(Glide.java:166) 
                                                       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:62) 
                                                       at com.bumptech.glide.RequestManager.<init>(RequestManager.java:53) 
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.fragmentGet(RequestManagerRetriever.java:171) 
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:127) 
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:89) 
                                                       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:91) 
                                                       at com.bumptech.glide.Glide.with(Glide.java:657) 
                                                       at com.dylanvann.fastimage.FastImageViewManager.setSrc(FastImageViewManager.java:143) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36) 
                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:770) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:855) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:46) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:900) 
                                                       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) 
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:582) 
                                                       at android.view.Choreographer.doFrame(Choreographer.java:551) 
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:755) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 
                                                    Caused by: java.lang.NoSuchMethodException
```

Environment:
- React : 16.0.0-alpha12
- React Native : 0.47.2
- RNFI : 1.0.0

Really need your help 

Thank You

**Comment by wz366** [comment]
How do you repro this?

**Comment by DylanVann** [comment]
I'd need more information to look into this more. 

Does the error still occur with the most recent version?

Do you have an existing version of Glide installed?
