### ISSUE TITLE
Crash on Play Store Due to Library Issue 

### ISSUE THREAD

**Issue by bhuvin25** [DylanVann/react-native-fast-image#764]
com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:122)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:10)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:36)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:14)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:55)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:23)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:47)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:53)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:31)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:46)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:2)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1088)
  at android.view.Choreographer.doCallbacks (Choreographer.java:913)
  at android.view.Choreographer.doFrame (Choreographer.java:836)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1075)
  at android.os.Handler.handleCallback (Handler.java:899)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:238)
  at android.app.ActivityThread.main (ActivityThread.java:7853)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:984)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Method.java)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:23)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:10)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:36)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:14)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:55)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:23)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:47)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:53)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:31)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:46)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:2)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1088)
  at android.view.Choreographer.doCallbacks (Choreographer.java:913)
  at android.view.Choreographer.doFrame (Choreographer.java:836)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1075)
  at android.os.Handler.handleCallback (Handler.java:899)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:238)
  at android.app.ActivityThread.main (ActivityThread.java:7853)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:984)
Caused by: java.lang.IllegalArgumentException:     at com.bumptech.glide.g.j.a(Unknown Source:11)
    at com.bumptech.glide.load.c.g.<init>(Unknown Source:6)
    at com.dylanvann.fastimage.e.f(Unknown Source:14)
    at com.dylanvann.fastimage.FastImageViewManager.setSrc(Unknown Source:30)
    ... 25 more

 

CPU usage from 31961ms to -1ms ago (2021-01-27 18:45:23.376 to 2021-01-27 18:45:55.338):
  19% 993/surfaceflinger: 11% user + 8.4% kernel / faults: 607 minor
  16% 1841/system_server: 10% user + 6.5% kernel / faults: 17717 minor 38 major
  5.6% 4133/com.google.android.apps.nbu.paisa.user: 4.1% user + 1.4% kernel / faults: 11126 minor 2 major
  5.2% 3286/com.oppo.launcher: 3.9% user + 1.2% kernel / faults: 11862 minor 91 major
  4.6% 31983/com.android.incallui: 2.9% user + 1.7% kernel / faults: 1380 minor
  4.1% 888/android.hardware.graphics.composer@2.3-service: 2.3% user + 1.8% kernel / faults: 334 minor
  2.7% 875/android.hardware.audio@2.0-service: 0% user + 2.7% kernel / faults: 357 minor 3 major
  2.4% 32679/com.google.android.gms.persistent: 1.5% user + 0.8% kernel / faults: 11322 minor 74 major
  2.4% 979/audioserver: 0% user + 2.4% kernel / faults: 220 minor 2 major
  2.4% 32424/com.android.systemui: 1.5% user + 0.8% kernel / faults: 2101 minor 8 major
  1.7% 3249/com.android.phone: 1.1% user + 0.5% kernel / faults: 1740 minor 9 major
  1.5% 150/kswapd0:0: 0% user + 1.5% kernel
  1.5% 151/kswapd0:1: 0% user + 1.5% kernel
  1.4% 355/mmc-cmdqd/0: 0% user + 1.4% kernel
  1.2% 259/crtc_commit:92: 0% user + 1.2% kernel
  1.2% 3345/com.coloros.persist.system: 0.6% user + 0.5% kernel / faults: 4964 minor 35 major
  1.1% 497/logd: 0.6% user + 0.5% kernel / faults: 189 minor 1 major
  1.1% 28656/kworker/u16:16: 0% user + 1.1% kernel
  0.9% 266/kgsl_worker_thr: 0% user + 0.9% kernel
  0.9% 8313/kworker/u16:7: 0% user + 0.9% kernel
  0.9% 18813/kworker/u16:15: 0% user + 0.9% kernel
  0.9% 32707/com.google.android.gms: 0.5% user + 0.3% kernel / faults: 3527 minor 1 major
  0.7% 902/android.hardware.sensors@2.0-service: 0.4% user + 0.3% kernel / faults: 265 minor
  0.7% 9/rcu_preempt: 0% user + 0.7% kernel
  0.1% 29709/com.android.vending: 0% user + 0% kernel / faults: 8494 minor 327 major
  0.6% 4299/irq/86-1b8e200.: 0% user + 0.6% kernel
  0.5% 308/irq/230-ilitek: 0% u

**Comment by DylanVann** [comment]
This crash came from building the Glide URL in the `source` prop setter. Since 8.5.5 (#782), a `uri` that can't be resolved fires `onError` instead. Please open a new issue if you still see this on the latest version.
