### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.Registry com.bumptech.glide.Registry.replace(java.lang.Class, java.lang.Class, 

### ISSUE THREAD

**Issue by harendrasaini01** [DylanVann/react-native-fast-image#962]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.bumptech.glide.Registry com.bumptech.glide.Registry.replace(java.lang.Class, java.lang.Class, com.bumptech.glide.load.model.ModelLoaderFactory)' on a null object reference
       at com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule.registerComponents(FastImageOkHttpProgressGlideModule.java:49)
       at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:34)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:329)
       at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)
       at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:210)
       at com.bumptech.glide.Glide.get(Glide.java:191)
       at com.bumptech.glide.Glide.getRetriever(Glide.java:774)
       at com.bumptech.glide.Glide.with(Glide.java:801)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java:53)
       at com.dylanvann.fastimage.FastImageViewManager.createViewInstance(FastImageViewManager.java:33)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:183)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mohamed2m2018** [comment]
happening with me too

**Comment by Jashanpreet1998** [comment]
i'm also facing same issue

**Comment by pawlitos** [comment]
If you get this issue in Sentry or other error tracking system and user's device is Nexus 5X then it comes from Google's bot used for review in Google Play. For some reason it crashes, but as long as your app passes the review you don't have to worry about it.

**Comment by ghost** [comment]
If you get this issue in Sentry or other error tracking system and user's device is a rooted Nexus 5X then it comes from Google's bot used for review in Google Play. For some reason it crashes, but as long as your app passes the review you don't have to worry about it.

**Comment by dhavalsulhuf** [comment]
I'm also facing same issue. any solution?
 "react": "17.0.2",
  "react-native": "0.66.3",
  
![Screenshot 2023-05-09 at 10 00 41 AM](https://user-images.githubusercontent.com/109509977/236994702-e2b85526-7957-43bc-a5ae-85e4b148d196.png)
