### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead

### ISSUE THREAD

**Issue by harendrasaini01** [DylanVann/react-native-fast-image#963]
Fatal Exception: java.lang.IllegalStateException: You cannot call Glide.get() in registerComponents(), use the provided Glide instance instead
       at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:205)
       at com.bumptech.glide.Glide.get(Glide.java:191)
       at com.dylanvann.fastimage.FastImageViewModule.clearDiskCache(FastImageViewModule.java:86)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Jashanpreet1998** [comment]
i'm also facing same issue
